# Generated by Django 3.1.7 on 2021-02-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210227_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
